### ISSUE TITLE
autocompleted items are not handled correctly

### ISSUE THREAD

**Issue by pgosar** [brenton-leighton/multiple-cursors.nvim#65] opened 2024-05-29 09:09 UTC
Great plugin! I think this issue I have is the last step before I can switch from vim-visual-multi.

![image](https://github.com/brenton-leighton/multiple-cursors.nvim/assets/55164602/4bf3d376-51de-4341-90c9-29974458b1fe)
![image](https://github.com/brenton-leighton/multiple-cursors.nvim/assets/55164602/b275124d-3ffb-45a9-9f86-20cefcb5352a)

As you can see, when auto-completing, the other cursors do not end up with the correct text, Neovim version 0.10.0. I'm not quite sure if I understood correctly, but I did add the pre and post hooks to the plugin setup in Lazy.nvim

Interestingly, I cannot repro this just given Neovim's default completion menu or even with nvim-cmp unless I setup a language server, it seems to happen only with suggestions given by the LSP?

Expected behavior is that whatever text is auto-completed on the "primary" cursor is replicated across all cursors - this does work with vim-visual-multi

**Comment by pgosar** [comment] 2024-05-29 10:01
Min repo.

`local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
local uv = vim.uv or vim.loop

-- Auto-install lazy.nvim if not present
if not uv.fs_stat(lazypath) then
	print("Installing lazy.nvim....")
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
	print("Done.")
end

vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	{ "VonHeikemen/lsp-zero.nvim", branch = "v3.x" },
	{ "williamboman/mason.nvim" },
	{ "williamboman/mason-lspconfig.nvim" },
	{ "neovim/nvim-lspconfig" },
	{ "hrsh7th/cmp-nvim-lsp" },
	{ "hrsh7th/nvim-cmp" },
	{
		"brenton-leighton/multiple-cursors.nvim",
		version = "*", -- Use the latest tagged version
		opts = {}, -- This causes the plugin setup function to be called
		keys = {
			{ "<C-j>", "<Cmd>MultipleCursorsAddDown<CR>", mode = { "n", "x" }, desc = "Add cursor and move down" },
			{ "<C-k>", "<Cmd>MultipleCursorsAddUp<CR>", mode = { "n", "x" }, desc = "Add cursor and move up" },
		},
	},
})

local lsp_zero = require("lsp-zero")

lsp_zero.on_attach(function(client, bufnr)
	lsp_zero.default_keymaps({ buffer = bufnr })
end)

require("mason").setup({})
require("mason-lspconfig").setup({
	handlers = {
		function(server_name)
			require("lspconfig")[server_name].setup({})
		end,
	},
})

local cmp = require("cmp")

cmp.setup({
	mapping = cmp.mapping.preset.insert({
		["<CR>"] = cmp.mapping.confirm({ select = false }),
		["<C-Space>"] = cmp.mapping.complete(),
	}),
})
`

**Comment by brenton-leighton** [comment] 2024-05-31 00:43
So you're using Neovim's in-built completion with a language server? I only tried the standard in-built completion, I'll have to test it with a language server to see what the problem is.

**Comment by pgosar** [comment] 2024-05-31 01:02
Yeah exactly. I think the problem might just be that the inbuilt completion
and lsp completion don’t share the same api

**Comment by brenton-leighton** [comment] 2024-05-31 01:10
> Yeah exactly. I think the problem might just be that the inbuilt completion and lsp completion don’t share the same api

Yeah that's most likely, but I can check and see if it can be supported.

**Comment by brenton-leighton** [comment] 2024-07-10 01:21
@pgosar I've tested using LSP and the omnifunction for completion (`Ctrl+x Ctrl+o`) and as far as I can tell it works fine (except for some weirdness with the up and down keys), so I think what you're describing is an issue with nvim-cmp. Can you try commenting out anything to do with nvim-cmp and see if you still have a problem?

**Comment by pgosar** [comment] 2024-07-10 16:09
Yeah like I mentioned I think something is going wrong with how nvim-cmp
formats its completions from a language server. It does work properly for
other cases where the completion does not come from a language server. For
what it’s worth
https://github.com/mg979/vim-visual-multi
does it correctly so maybe that’s something to look into. Unfortunately i’m
not super familiar with how it works though

**Comment by brenton-leighton** [comment] 2024-12-31 03:04
Hey I'm going to close this issue as I'm not motivated to figure out how to get this plugin working with nvim-cmp. Built-in auto-completion is coming to 0.11 and it should work with this plugin, given that manual completion works.

**Comment by brenton-leighton** [comment] 2024-12-31 03:04
Hey I'm going to close this issue as I'm not motivated to figure out how to get this plugin working with nvim-cmp. Built-in auto-completion is coming to 0.11 and it should work with this plugin, given that manual completion works.

**Closed by brenton-leighton** 2024-12-31 03:04 UTC
